package:
  name: petsc
  version: "3.7.2"

source:
  fn: petsc-lite-3.7.2.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.2.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - openblas
    - mpi4py
    - gcc

  run:
    - python
    - openblas
    - mpi4py
    - libgcc

test:
  requires:
    - gcc

about:
  home: http://www.mcs.anl.gov/petsc/
  license: PETSc
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
