package:
  name: eigen3
  version: "3.2.8"

source:
  fn: eigen3-3.2.8.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.2.8.tar.gz

build:
  number: 0

requirements:
  build:
    - gcc
    - cmake

  run:
    - libgcc

test:
  requires:
    - gcc

  files:
    - test.cc

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
