package:
  name: swig
  version: 3.0.10

source:
  fn: swig-3.0.10.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.10.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - gcc
    - zlib
    - pcre
    - python

  run:
    - libgcc
    - zlib
    - pcre

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
