package:
  name: ffc
  version: "1.6.0"

source:
  fn: ffc-1.6.0.tar.gz
  url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-1.6.0.tar.gz
  md5: 358faa3e9da62a1b1a717070217b793e

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - swig
    - gcc
    - libgfortran

  run:
    - python
    - numpy
    - swig
    - ufl
    - fiat
    - instant
    - libgcc
    - libgfortran

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'The FEniCS Form Compiler'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
