package:
  name: slepc
  version: "3.7.1"

source:
  fn: v3.7.1.tar.gz
  url: https://bitbucket.org/slepc/slepc/get/v3.7.1.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - gcc
    - petsc

  run:
    - python
    - libgcc
    - petsc

test:
  requires:
    - gcc

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
