package:
  name: dolfin
  version: "1.6.0.dev"

source:
  fn: master.tar.gz
  url: https://bitbucket.org/fenics-project/dolfin/get/master.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - openblas
    - cmake
    - sphinx
    - libxml2
    - swig
    - numpy
    - ffc ==1.6.0
    - ply
    - boost
    - eigen3
    - petsc
    - petsc4py
    - slepc <=3.6.2

  run:
    - python
    - openblas
    - libxml2
    - swig
    - numpy
    #- vtk
    - ffc ==1.6.0
    - ufl ==1.6.0
    - ply
    - boost
    - eigen3
    - petsc
    - petsc4py
    - slepc <=3.6.2

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
